import { GENERATORS } from '@/src/game/content/generators';
import { UpgradeDef } from '@/src/game/sim/messages';

const tierThresholds = [10, 25, 50, 100] as const;
const tierCostMultipliers = [140, 1_200, 11_000, 130_000] as const;

const generatorTierUpgrades: UpgradeDef[] = GENERATORS.flatMap((generator) =>
  tierThresholds.map((threshold, index) => {
    const tierNumber = index + 1;
    return {
      id: `${generator.id}-tier-${tierNumber}`,
      name: `${generator.name} Calibration ${tierNumber}`,
      effectLine: `${generator.name} x2`,
      description: `Double ${generator.name} output.`,
      cost: Math.round(generator.baseCost * tierCostMultipliers[index]),
      currency: 'chronons',
      category: 'generator',
      type: 'generatorTierMultiplier',
      value: 2,
      generatorId: generator.id,
      unlock: {
        generatorsOwned: {
          [generator.id]: threshold,
        },
      },
      iconPath: generator.iconPath,
    } satisfies UpgradeDef;
  }),
);

const synergyUpgrades: UpgradeDef[] = [
  {
    id: 'synergy-anchor-shard',
    name: 'Anchored Crystals',
    effectLine: 'Time Anchor empowers Chrono Shard (+0.6% each)',
    description: 'Each Time Anchor increases Chrono Shard output by 0.6%.',
    cost: 220_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.006,
    generatorId: 'chronoShard',
    sourceGeneratorId: 'timeAnchor',
    unlock: { generatorsOwned: { chronoShard: 25, timeAnchor: 25 } },
    iconPath: '/assets/time-loop/icon_time_anchor.png',
  },
  {
    id: 'synergy-engine-anchor',
    name: 'Recursive Anchoring',
    effectLine: 'Loop Engine empowers Time Anchor (+0.55% each)',
    description: 'Each Loop Engine increases Time Anchor output by 0.55%.',
    cost: 900_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.0055,
    generatorId: 'timeAnchor',
    sourceGeneratorId: 'loopEngine',
    unlock: { generatorsOwned: { timeAnchor: 40, loopEngine: 25 } },
    iconPath: '/assets/time-loop/icon_loop_engine.png',
  },
  {
    id: 'synergy-hourglass-engine',
    name: 'Sandblasted Pistons',
    effectLine: 'Hourglass Protocol empowers Loop Engine (+0.5% each)',
    description: 'Each Hourglass Protocol increases Loop Engine output by 0.5%.',
    cost: 2_700_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.005,
    generatorId: 'loopEngine',
    sourceGeneratorId: 'hourglassProtocol',
    unlock: { generatorsOwned: { loopEngine: 50, hourglassProtocol: 30 } },
    iconPath: '/assets/time-loop/icon_hourglass_protocol.png',
  },
  {
    id: 'synergy-anomaly-hourglass',
    name: 'Anomalous Sandflow',
    effectLine: 'Temporal Anomaly empowers Hourglass Protocol (+0.45% each)',
    description: 'Each Temporal Anomaly increases Hourglass Protocol output by 0.45%.',
    cost: 9_000_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.0045,
    generatorId: 'hourglassProtocol',
    sourceGeneratorId: 'temporalAnomaly',
    unlock: { generatorsOwned: { hourglassProtocol: 50, temporalAnomaly: 35 } },
    iconPath: '/assets/time-loop/icon_temporal_anomaly.png',
  },
  {
    id: 'synergy-core-anomaly',
    name: 'Core Distortion Mesh',
    effectLine: 'Paradox Core empowers Temporal Anomaly (+0.4% each)',
    description: 'Each Paradox Core increases Temporal Anomaly output by 0.4%.',
    cost: 24_000_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.004,
    generatorId: 'temporalAnomaly',
    sourceGeneratorId: 'paradoxCore',
    unlock: { generatorsOwned: { temporalAnomaly: 60, paradoxCore: 30 } },
    iconPath: '/assets/time-loop/icon_paradox_core.png',
  },
  {
    id: 'synergy-core-shard',
    name: 'Paradox Crystal Resonance',
    effectLine: 'Paradox Core empowers Chrono Shard (+0.25% each)',
    description: 'Each Paradox Core increases Chrono Shard output by 0.25%.',
    cost: 36_000_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.0025,
    generatorId: 'chronoShard',
    sourceGeneratorId: 'paradoxCore',
    unlock: { generatorsOwned: { chronoShard: 100, paradoxCore: 40 } },
    iconPath: '/assets/time-loop/icon_paradox_core.png',
  },
];

const clickUpgrades: UpgradeDef[] = [
  {
    id: 'click-tuned-finger',
    name: 'Tuned Fingerwork',
    effectLine: 'Click power +1',
    description: 'A steadier rhythm squeezes extra Chronons from each click.',
    cost: 30,
    currency: 'chronons',
    category: 'click',
    type: 'clickFlat',
    value: 1,
    unlock: { totalChrononsEarned: 30 },
  },
  {
    id: 'click-impulse-gloves',
    name: 'Impulse Gloves',
    effectLine: 'Click power +2',
    description: 'Chrono-threaded gloves boost manual impact.',
    cost: 220,
    currency: 'chronons',
    category: 'click',
    type: 'clickFlat',
    value: 2,
    unlock: { totalChrononsEarned: 180 },
  },
  {
    id: 'click-resonant-knuckles',
    name: 'Resonant Knuckles',
    effectLine: 'Click power +5',
    description: 'A resonance shell amplifies each strike.',
    cost: 1_800,
    currency: 'chronons',
    category: 'click',
    type: 'clickFlat',
    value: 5,
    unlock: { totalChrononsEarned: 1_100 },
  },
  {
    id: 'click-burst-cadence',
    name: 'Burst Cadence',
    effectLine: 'Click power +10',
    description: 'Rapid cadence trains your loop reflexes.',
    cost: 14_000,
    currency: 'chronons',
    category: 'click',
    type: 'clickFlat',
    value: 10,
    unlock: { totalChrononsEarned: 8_000 },
  },
  {
    id: 'click-dual-pulse',
    name: 'Dual Pulse Strikes',
    effectLine: 'Click power x2',
    description: 'Every click propagates as a paired pulse.',
    cost: 110_000,
    currency: 'chronons',
    category: 'click',
    type: 'clickMultiplier',
    value: 2,
    unlock: { totalChrononsEarned: 70_000 },
  },
  {
    id: 'click-shard-feedback',
    name: 'Shard Feedback Loop',
    effectLine: 'Each Chrono Shard adds +0.2% click power',
    description: 'Chrono Shards feed tiny bursts into manual input.',
    cost: 260_000,
    currency: 'chronons',
    category: 'click',
    type: 'clickSynergy',
    value: 0.002,
    sourceGeneratorId: 'chronoShard',
    unlock: { generatorsOwned: { chronoShard: 50 } },
    iconPath: '/assets/time-loop/icon_chrono_shard.png',
  },
  {
    id: 'click-engine-reflex',
    name: 'Engine Reflex Coupling',
    effectLine: 'Each Loop Engine adds +0.3% click power',
    description: 'Loop Engine timing is piped into your reflex window.',
    cost: 1_600_000,
    currency: 'chronons',
    category: 'click',
    type: 'clickSynergy',
    value: 0.003,
    sourceGeneratorId: 'loopEngine',
    unlock: { generatorsOwned: { loopEngine: 40 } },
    iconPath: '/assets/time-loop/icon_loop_engine.png',
  },
  {
    id: 'click-temporal-overdrive',
    name: 'Temporal Overdrive',
    effectLine: 'Click power x2',
    description: 'Manual actions split into dual-timeline impacts.',
    cost: 6_200_000,
    currency: 'chronons',
    category: 'click',
    type: 'clickMultiplier',
    value: 2,
    unlock: { totalChrononsEarned: 4_000_000 },
  },
  {
    id: 'click-anomaly-snap',
    name: 'Anomaly Snapback',
    effectLine: 'Click power +50',
    description: 'Collapsed anomalies release dense click energy.',
    cost: 14_000_000,
    currency: 'chronons',
    category: 'click',
    type: 'clickFlat',
    value: 50,
    unlock: { generatorsOwned: { temporalAnomaly: 35 } },
    iconPath: '/assets/time-loop/icon_temporal_anomaly.png',
  },
];

const globalMilestoneUpgrades: UpgradeDef[] = [
  {
    id: 'global-temporal-ledger',
    name: 'Temporal Ledger',
    effectLine: 'Global production x1.05',
    description: 'Improved accounting across timelines.',
    cost: 16_000,
    currency: 'chronons',
    category: 'global',
    type: 'globalMultiplier',
    value: 1.05,
    unlock: { totalChrononsEarned: 18_000 },
  },
  {
    id: 'global-epoch-index',
    name: 'Epoch Index',
    effectLine: 'Global production x1.08',
    description: 'Cataloged loops compound efficiency.',
    cost: 90_000,
    currency: 'chronons',
    category: 'global',
    type: 'globalMultiplier',
    value: 1.08,
    unlock: { totalChrononsEarned: 100_000 },
  },
  {
    id: 'global-density-map',
    name: 'Chronon Density Map',
    effectLine: 'Global production x1.12',
    description: 'Map rich time seams for all operations.',
    cost: 420_000,
    currency: 'chronons',
    category: 'global',
    type: 'globalMultiplier',
    value: 1.12,
    unlock: { totalChrononsEarned: 700_000 },
  },
  {
    id: 'global-cost-compression-i',
    name: 'Cost Compression I',
    effectLine: 'Reduce generator growth by 0.004',
    description: 'Tighter build tolerances lower expansion costs.',
    cost: 2_000_000,
    currency: 'chronons',
    category: 'global',
    type: 'costCompression',
    value: 0.004,
    unlock: { totalChrononsEarned: 2_200_000 },
    iconPath: '/assets/time-loop/upgrade_cost_compression.png',
  },
  {
    id: 'global-distant-pulse',
    name: 'Distant Pulse Relay',
    effectLine: 'Global production x1.18',
    description: 'Transmit stable pulses across distant loops.',
    cost: 8_500_000,
    currency: 'chronons',
    category: 'global',
    type: 'globalMultiplier',
    value: 1.18,
    unlock: { totalChrononsEarned: 12_000_000 },
  },
  {
    id: 'global-scheduler',
    name: 'Autoloop Scheduler',
    effectLine: '+1 passive click / sec',
    description: 'Background loop scheduling adds steady clicks.',
    cost: 17_000_000,
    currency: 'chronons',
    category: 'automation',
    type: 'autoClick',
    value: 1,
    unlock: { totalChrononsEarned: 25_000_000 },
    iconPath: '/assets/time-loop/upgrade_autoloop.png',
  },
  {
    id: 'global-cost-compression-ii',
    name: 'Cost Compression II',
    effectLine: 'Reduce generator growth by 0.006',
    description: 'Nested blueprints suppress scaling overhead.',
    cost: 42_000_000,
    currency: 'chronons',
    category: 'global',
    type: 'costCompression',
    value: 0.006,
    unlock: { totalChrononsEarned: 70_000_000 },
    iconPath: '/assets/time-loop/upgrade_cost_compression.png',
  },
  {
    id: 'global-chronoweave',
    name: 'Chronoweave Mesh',
    effectLine: 'Global production x1.25',
    description: 'Cross-linked loops hold a stronger baseline.',
    cost: 95_000_000,
    currency: 'chronons',
    category: 'global',
    type: 'globalMultiplier',
    value: 1.25,
    unlock: { totalChrononsEarned: 150_000_000 },
  },
];

const automationUpgrades: UpgradeDef[] = [
  {
    id: 'autoloop',
    name: 'Autoloop',
    effectLine: '+1 passive click / sec',
    description: 'Generates 1 passive click per second.',
    cost: 7_000,
    currency: 'chronons',
    category: 'automation',
    type: 'autoClick',
    value: 1,
    unlock: { generatorsOwned: { chronoShard: 12 } },
    iconPath: '/assets/time-loop/upgrade_autoloop.png',
  },
];

export const UPGRADES: UpgradeDef[] = [
  ...generatorTierUpgrades,
  ...synergyUpgrades,
  ...clickUpgrades,
  ...globalMilestoneUpgrades,
  ...automationUpgrades,
];
