import { GENERATORS } from '@/src/game/content/generators';
import { UpgradeDef } from '@/src/game/sim/messages';

const tierThresholds = [10, 25, 50, 100] as const;
const tierCostMultipliers = [100, 900, 7_000, 65_000] as const;

const generatorTierUpgrades: UpgradeDef[] = GENERATORS.flatMap((generator) =>
  tierThresholds.map((threshold, index) => {
    const tierNumber = index + 1;
    return {
      id: `${generator.id}-tier-${tierNumber}`,
      name: `${generator.name} Calibration ${tierNumber}`,
      effectLine: `${generator.name} x2`,
      description: `Double ${generator.name} output.`,
      cost: Math.round(generator.baseCost * tierCostMultipliers[index]),
      currency: 'chronons',
      category: 'generator',
      type: 'generatorTierMultiplier',
      value: 2,
      generatorId: generator.id,
      unlock: {
        generatorsOwned: {
          [generator.id]: threshold,
        },
      },
      iconPath: generator.iconPath,
    } satisfies UpgradeDef;
  }),
);

const synergyUpgrades: UpgradeDef[] = [
  {
    id: 'synergy-anchor-shard',
    name: 'Anchored Crystals',
    effectLine: 'Time Anchor empowers Chrono Shard (+1% each)',
    description: 'Each Time Anchor increases Chrono Shard output by 1%.',
    cost: 110_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.01,
    generatorId: 'chronoShard',
    sourceGeneratorId: 'timeAnchor',
    unlock: { generatorsOwned: { chronoShard: 25, timeAnchor: 25 } },
    iconPath: '/assets/time-loop/icon_time_anchor.png',
  },
  {
    id: 'synergy-engine-anchor',
    name: 'Recursive Anchoring',
    effectLine: 'Loop Engine empowers Time Anchor (+0.9% each)',
    description: 'Each Loop Engine increases Time Anchor output by 0.9%.',
    cost: 420_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.009,
    generatorId: 'timeAnchor',
    sourceGeneratorId: 'loopEngine',
    unlock: { generatorsOwned: { timeAnchor: 40, loopEngine: 25 } },
    iconPath: '/assets/time-loop/icon_loop_engine.png',
  },
  {
    id: 'synergy-hourglass-engine',
    name: 'Sandblasted Pistons',
    effectLine: 'Hourglass Protocol empowers Loop Engine (+0.85% each)',
    description: 'Each Hourglass Protocol increases Loop Engine output by 0.85%.',
    cost: 1_300_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.0085,
    generatorId: 'loopEngine',
    sourceGeneratorId: 'hourglassProtocol',
    unlock: { generatorsOwned: { loopEngine: 50, hourglassProtocol: 30 } },
    iconPath: '/assets/time-loop/icon_hourglass_protocol.png',
  },
  {
    id: 'synergy-anomaly-hourglass',
    name: 'Anomalous Sandflow',
    effectLine: 'Temporal Anomaly empowers Hourglass Protocol (+0.8% each)',
    description: 'Each Temporal Anomaly increases Hourglass Protocol output by 0.8%.',
    cost: 4_800_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.008,
    generatorId: 'hourglassProtocol',
    sourceGeneratorId: 'temporalAnomaly',
    unlock: { generatorsOwned: { hourglassProtocol: 50, temporalAnomaly: 35 } },
    iconPath: '/assets/time-loop/icon_temporal_anomaly.png',
  },
  {
    id: 'synergy-core-anomaly',
    name: 'Core Distortion Mesh',
    effectLine: 'Paradox Core empowers Temporal Anomaly (+0.75% each)',
    description: 'Each Paradox Core increases Temporal Anomaly output by 0.75%.',
    cost: 16_000_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.0075,
    generatorId: 'temporalAnomaly',
    sourceGeneratorId: 'paradoxCore',
    unlock: { generatorsOwned: { temporalAnomaly: 60, paradoxCore: 30 } },
    iconPath: '/assets/time-loop/icon_paradox_core.png',
  },
  {
    id: 'synergy-core-shard',
    name: 'Paradox Crystal Resonance',
    effectLine: 'Paradox Core empowers Chrono Shard (+0.5% each)',
    description: 'Each Paradox Core increases Chrono Shard output by 0.5%.',
    cost: 24_000_000,
    currency: 'chronons',
    category: 'synergy',
    type: 'generatorSynergy',
    value: 0.005,
    generatorId: 'chronoShard',
    sourceGeneratorId: 'paradoxCore',
    unlock: { generatorsOwned: { chronoShard: 100, paradoxCore: 40 } },
    iconPath: '/assets/time-loop/icon_paradox_core.png',
  },
];

const globalMilestoneUpgrades: UpgradeDef[] = [
  {
    id: 'global-temporal-ledger',
    name: 'Temporal Ledger',
    effectLine: 'Global production x1.08',
    description: 'Improved accounting across timelines.',
    cost: 8_000,
    currency: 'chronons',
    category: 'global',
    type: 'globalMultiplier',
    value: 1.08,
    unlock: { totalChrononsEarned: 10_000 },
  },
  {
    id: 'global-epoch-index',
    name: 'Epoch Index',
    effectLine: 'Global production x1.1',
    description: 'Cataloged loops compound efficiency.',
    cost: 40_000,
    currency: 'chronons',
    category: 'global',
    type: 'globalMultiplier',
    value: 1.1,
    unlock: { totalChrononsEarned: 50_000 },
  },
  {
    id: 'global-reinforced-clicks',
    name: 'Reinforced Click Routines',
    effectLine: 'Click power x1.2',
    description: 'Manual interventions gain force.',
    cost: 120_000,
    currency: 'chronons',
    category: 'global',
    type: 'clickMultiplier',
    value: 1.2,
    unlock: { totalChrononsEarned: 250_000 },
    iconPath: '/assets/time-loop/upgrade_reinforced_seconds.png',
  },
  {
    id: 'global-density-map',
    name: 'Chronon Density Map',
    effectLine: 'Global production x1.12',
    description: 'Map rich time seams for all operations.',
    cost: 300_000,
    currency: 'chronons',
    category: 'global',
    type: 'globalMultiplier',
    value: 1.12,
    unlock: { totalChrononsEarned: 1_000_000 },
  },
  {
    id: 'global-cost-compression-i',
    name: 'Cost Compression I',
    effectLine: 'Reduce generator growth by 0.008',
    description: 'Tighter build tolerances lower expansion costs.',
    cost: 1_200_000,
    currency: 'chronons',
    category: 'global',
    type: 'costCompression',
    value: 0.008,
    unlock: { totalChrononsEarned: 5_000_000 },
    iconPath: '/assets/time-loop/upgrade_cost_compression.png',
  },
  {
    id: 'global-distant-pulse',
    name: 'Distant Pulse Relay',
    effectLine: 'Global production x1.15',
    description: 'Transmit stable pulses across distant loops.',
    cost: 4_500_000,
    currency: 'chronons',
    category: 'global',
    type: 'globalMultiplier',
    value: 1.15,
    unlock: { totalChrononsEarned: 25_000_000 },
  },
  {
    id: 'global-scheduler',
    name: 'Autoloop Scheduler',
    effectLine: '+2 passive clicks / sec',
    description: 'Background loop scheduling adds steady clicks.',
    cost: 12_000_000,
    currency: 'chronons',
    category: 'automation',
    type: 'autoClick',
    value: 2,
    unlock: { totalChrononsEarned: 60_000_000 },
    iconPath: '/assets/time-loop/upgrade_autoloop.png',
  },
  {
    id: 'global-cost-compression-ii',
    name: 'Cost Compression II',
    effectLine: 'Reduce generator growth by 0.01',
    description: 'Nested blueprints suppress scaling overhead.',
    cost: 35_000_000,
    currency: 'chronons',
    category: 'global',
    type: 'costCompression',
    value: 0.01,
    unlock: { totalChrononsEarned: 150_000_000 },
    iconPath: '/assets/time-loop/upgrade_cost_compression.png',
  },
];

const automationUpgrades: UpgradeDef[] = [
  {
    id: 'autoloop',
    name: 'Autoloop',
    effectLine: '+1 passive click / sec',
    description: 'Generates 1 passive click per second.',
    cost: 3_500,
    currency: 'chronons',
    category: 'automation',
    type: 'autoClick',
    value: 1,
    unlock: { generatorsOwned: { chronoShard: 10 } },
    iconPath: '/assets/time-loop/upgrade_autoloop.png',
  },
];

export const UPGRADES: UpgradeDef[] = [
  ...generatorTierUpgrades,
  ...synergyUpgrades,
  ...globalMilestoneUpgrades,
  ...automationUpgrades,
];
