import { UpgradeDef } from '@/src/game/sim/messages';

export const UPGRADES: UpgradeDef[] = [
  {
    id: 'reinforced-seconds',
    name: 'Reinforced Seconds',
    description: 'Global production x1.2',
    cost: 100,
    currency: 'seconds',
    type: 'globalMultiplier',
    value: 1.2,
    iconPath: '/assets/time-loop/upgrade_reinforced_seconds.png',
  },
  {
    id: 'minute-hand',
    name: 'Minute Hand',
    description: 'Unlock minutes and auto-conversion controls',
    cost: 300,
    currency: 'seconds',
    type: 'unlockMinutes',
    value: 1,
  },
  {
    id: 'temporal-efficiency',
    name: 'Temporal Efficiency',
    description: 'Generator output x1.25',
    cost: 4,
    currency: 'minutes',
    type: 'generatorMultiplier',
    value: 1.25,
  },
  {
    id: 'autoloop',
    name: 'Autoloop',
    description: 'Clicks once per second automatically',
    cost: 6,
    currency: 'minutes',
    type: 'autoClick',
    value: 1,
    iconPath: '/assets/time-loop/upgrade_autoloop.png',
  },
  {
    id: 'hourglass-protocol',
    name: 'Hourglass Protocol',
    description: 'Unlock hours conversion chain',
    cost: 20,
    currency: 'minutes',
    type: 'unlockHours',
    value: 1,
  },
  {
    id: 'cost-compression-i',
    name: 'Cost Compression I',
    description: 'Reduce generator growth exponents slightly',
    cost: 15,
    currency: 'minutes',
    type: 'costCompression',
    value: 0.01,
    iconPath: '/assets/time-loop/upgrade_cost_compression.png',
  },
  {
    id: 'clockwork-lattice',
    name: 'Clockwork Lattice',
    description: 'Global production x1.35',
    cost: 45,
    currency: 'minutes',
    type: 'globalMultiplier',
    value: 1.35,
  },
  {
    id: 'anchor-overdrive',
    name: 'Anchor Overdrive',
    description: 'Generator output x1.3',
    cost: 1,
    currency: 'hours',
    type: 'generatorMultiplier',
    value: 1.3,
  },
  {
    id: 'autoloop-ii',
    name: 'Autoloop II',
    description: 'Additional auto-click each second',
    cost: 2,
    currency: 'hours',
    type: 'autoClick',
    value: 1,
  },
  {
    id: 'second-symmetry',
    name: 'Second Symmetry',
    description: 'Global production x1.5',
    cost: 3,
    currency: 'hours',
    type: 'globalMultiplier',
    value: 1.5,
  },
  {
    id: 'cost-compression-ii',
    name: 'Cost Compression II',
    description: 'Further reduce growth exponents',
    cost: 4,
    currency: 'hours',
    type: 'costCompression',
    value: 0.015,
    iconPath: '/assets/time-loop/upgrade_cost_compression.png',
  },
  {
    id: 'fractal-scheduler',
    name: 'Fractal Scheduler',
    description: 'Generator output x1.45',
    cost: 5,
    currency: 'hours',
    type: 'generatorMultiplier',
    value: 1.45,
  },
];
